version: '3.8'

networks: 
  observability_net:
    driver: bridge

volumes:
  mysql_data: # Named volume

services:
  database:
    image: mysql:8.0
    container_name: demo_mysql
    environment:  # Cac thiet lap ban dau
      - MYSQL_ROOT_PASSWORD=rootpassword  # Tao mat khau cho root
      - MYSQL_DATABASE=shop_db  # Tao database rong shop_db de bom init.sql
      - MYSQL_USER=app_user # Tao user trong app
      - MYSQL_PASSWORD=app_password
    volumes:
      - mysql_data:/var/lib/mysql # Named volume
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Bind mount
    networks:
      - observability_net

  backend-app:
    build: 
      context: ./target-app
    container_name: demo_backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database  # Su dung host la database duoc khai bao o tren
      - DB_USER=app_user
      - DB_PASSWORD=app_password
      - OTLP_ENDPOINT=alloy:4317
    volumes:
      - ./target-app/logs:/app/logs 
    depends_on:
      - database 
    networks:
      - observability_net

  nginx: 
    image: nginx:alpine
    container_name: demo_nginx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend-app
    networks:
      - observability_net

  alloy:
    image: grafana/alloy:latest
    container_name: demo_alloy
    ports:
      - "4317:4317" # Port gRPC 
      - "4318:4318" # Port HTTP 
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy 
      - ./target-app/logs:/var/log/app 
      - ./nginx/logs:/var/log/nginx 
    command: 
      - run
      - /etc/alloy/config.alloy 
    depends_on:
      - nginx
    networks:
      - observability_net