{
 "title": "Tổng quan Lưu lượng",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fastapi_requests_total{job=\"fastapi-backend\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tốc độ xử lý Request (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(fastapi_requests_duration_seconds_sum{job=\"fastapi-backend\"}[1m])) \r\n/ \r\nsum by (path) (rate(fastapi_requests_duration_seconds_count{job=\"fastapi-backend\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fastapi_exceptions_total{job=\"fastapi-backend\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(fastapi_requests_total{job=\"fastapi-backend\"}[1m]))"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(fastapi_requests_duration_seconds_bucket{job=\"fastapi-backend\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"fastapi-backend\"} | json [1m]))"
    }
   ]
  },
  {
   "title": "Logs of fastapi-backend",
   "type": "logs",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fastapi-backend\"}"
    }
   ]
  },
  {
   "title": "Request Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"backend-app\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}